import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import EditorialHeader from "@/components/functional/EditorialHeader/EditorialHeader";
import Footer from "@/components/functional/Footer/Footer";

const polySans = localFont({
  src: [
    {
      path: "./fonts/polysanstrial-slim-webfont.woff2",
      weight: "400",
      style: "normal",
    },
    {
      path: "./fonts/polysanstrial-neutral-webfont.woff2",
      weight: "400",
      style: "normal",
    },
    {
      path: "./fonts/polysanstrial-median-webfont.woff2",
      weight: "400",
      style: "normal",
    },
  ],
  variable: "--font-polysans",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${polySans.variable} antialiased`}>
        <EditorialHeader />
        {children}
        <Footer />
      </body>
    </html>
  );
}
